
import os
import sqlite3
from urllib.parse import urlparse

from flask import (
    Flask, render_template, request,
    redirect, url_for, flash
)

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "local-development-key")

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()


def get_db():
    """Use PostgreSQL in the cloud when DATABASE_URL is configured.
    Otherwise use SQLite locally.
    """
    if DATABASE_URL:
        import psycopg
        from psycopg.rows import dict_row

        url = DATABASE_URL.replace(
            "postgres://", "postgresql://", 1
        )
        return psycopg.connect(url, row_factory=dict_row)

    conn = sqlite3.connect("exam.db")
    conn.row_factory = sqlite3.Row
    return conn


def initialize_database():
    conn = get_db()

    statements = [
        """
        CREATE TABLE IF NOT EXISTS exams (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            description TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS questions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            exam_id INTEGER NOT NULL REFERENCES exams(id),
            question TEXT NOT NULL,
            option_a TEXT NOT NULL,
            option_b TEXT NOT NULL,
            option_c TEXT NOT NULL,
            option_d TEXT NOT NULL,
            correct_answer TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS results (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            student_name TEXT NOT NULL,
            exam_id INTEGER NOT NULL REFERENCES exams(id),
            score INTEGER NOT NULL,
            total INTEGER NOT NULL
        )
        """
    ]

    # SQLite uses a different syntax for auto-incrementing IDs.
    if not DATABASE_URL:
        statements = [
            """
            CREATE TABLE IF NOT EXISTS exams (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                description TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS questions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                exam_id INTEGER NOT NULL,
                question TEXT NOT NULL,
                option_a TEXT NOT NULL,
                option_b TEXT NOT NULL,
                option_c TEXT NOT NULL,
                option_d TEXT NOT NULL,
                correct_answer TEXT NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS results (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                student_name TEXT NOT NULL,
                exam_id INTEGER NOT NULL,
                score INTEGER NOT NULL,
                total INTEGER NOT NULL
            )
            """
        ]

    try:
        for statement in statements:
            conn.execute(statement)

        count = conn.execute(
            "SELECT COUNT(*) AS count FROM exams"
        ).fetchone()["count"]

        if count == 0:
            cursor = conn.execute(
                "INSERT INTO exams (title, description) "
                "VALUES (%s, %s)" if DATABASE_URL
                else "INSERT INTO exams (title, description) VALUES (?, ?)",
                ("Cloud Computing Fundamentals",
                 "Test your knowledge of cloud computing.")
            )
            exam_id = (
                cursor.fetchone()["id"]
                if DATABASE_URL
                else cursor.lastrowid
            )

            sample_questions = [
                (exam_id, "What does IaaS stand for?",
                 "Internet as a Service",
                 "Infrastructure as a Service",
                 "Information as a Service",
                 "Integration as a Service", "B"),
                (exam_id, "Which model provides software online?",
                 "IaaS", "PaaS", "SaaS", "LAN", "C"),
                (exam_id, "Which Python framework does this project use?",
                 "Flask", "React", "Bootstrap", "Notepad", "A"),
                (exam_id, "Which database is used locally?",
                 "Excel", "SQLite", "PowerPoint", "HTML", "B"),
                (exam_id, "Which is a cloud platform?",
                 "Notepad", "Calculator", "AWS", "Paint", "C")
            ]

            placeholder = "%s" if DATABASE_URL else "?"
            conn.executemany(
                f"""
                INSERT INTO questions
                (exam_id, question, option_a, option_b,
                 option_c, option_d, correct_answer)
                VALUES ({placeholder}, {placeholder}, {placeholder},
                        {placeholder}, {placeholder}, {placeholder},
                        {placeholder})
                """,
                sample_questions
            )

        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


@app.route("/")
def home():
    conn = get_db()
    try:
        exams = conn.execute(
            "SELECT * FROM exams ORDER BY id"
        ).fetchall()
    finally:
        conn.close()

    return render_template("index.html", exams=exams)


@app.route("/exam/<int:exam_id>", methods=["GET", "POST"])
def exam(exam_id):
    conn = get_db()

    try:
        exam_data = conn.execute(
            "SELECT * FROM exams WHERE id = %s" if DATABASE_URL
            else "SELECT * FROM exams WHERE id = ?",
            (exam_id,)
        ).fetchone()

        if exam_data is None:
            return "Exam not found", 404

        questions = conn.execute(
            "SELECT * FROM questions WHERE exam_id = %s ORDER BY id"
            if DATABASE_URL
            else "SELECT * FROM questions WHERE exam_id = ? ORDER BY id",
            (exam_id,)
        ).fetchall()

        if request.method == "GET":
            return render_template(
                "exam.html", exam=exam_data, questions=questions
            )

        student_name = request.form.get("student_name", "").strip()

        if not student_name:
            flash("Please enter your name.")
            return redirect(url_for("exam", exam_id=exam_id))

        if not questions:
            return "This exam has no questions.", 400

        score = 0
        for question in questions:
            selected = request.form.get(str(question["id"]), "")
            if selected == question["correct_answer"]:
                score += 1

        placeholder = "%s" if DATABASE_URL else "?"
        conn.execute(
            f"""
            INSERT INTO results
            (student_name, exam_id, score, total)
            VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder})
            """,
            (student_name, exam_id, score, len(questions))
        )
        conn.commit()

        return render_template(
            "result.html",
            student_name=student_name,
            score=score,
            total=len(questions)
        )
    finally:
        conn.close()


@app.route("/results")
def results():
    conn = get_db()
    try:
        records = conn.execute(
            """
            SELECT results.*, exams.title
            FROM results
            JOIN exams ON results.exam_id = exams.id
            ORDER BY results.id DESC
            """
        ).fetchall()
    finally:
        conn.close()

    return render_template("results.html", results=records)


@app.route("/cloud-models")
def cloud_models():
    return render_template("cloud_models.html")


@app.route("/health")
def health():
    return {"status": "ok"}


if __name__ == "__main__":
    initialize_database()
    app.run(
        host="0.0.0.0",
        port=int(os.environ.get("PORT", 5000)),
        debug=False
    )